import { pgTable, text, integer, real, boolean, jsonb } from 'drizzle-orm/pg-core';

export const breeders = pgTable('breeders', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  businessName: text('business_name'),
  email: text('email'),
  phone: text('phone'),
  website: text('website'),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  zipCode: text('zip_code'),
  country: text('country'),
  breeds: jsonb('breeds').$type<string[]>(),
  breedIds: jsonb('breed_ids').$type<number[]>(),
  experience: integer('experience'),
  rating: real('rating'),
  reviewCount: integer('review_count'),
  coverImage: text('cover_image'),
  about: text('about'),
  certifications: jsonb('certifications').$type<string[]>(),
  healthTesting: jsonb('health_testing').$type<string[]>(),
  specialties: jsonb('specialties').$type<string[]>(),
  currentLitters: integer('current_litters'),
  availablePuppies: integer('available_puppies'),
  pricing: text('pricing'),
  shipping: boolean('shipping'),
  pickupAvailable: boolean('pickup_available'),
  establishedYear: integer('established_year'),
  businessHours: text('business_hours'),
  appointmentRequired: boolean('appointment_required'),
  socialMedia: jsonb('social_media').$type<Record<string, string>>(),
  tags: jsonb('tags').$type<string[]>(),
  responseRate: real('response_rate'),
  avgResponseTime: text('avg_response_time'),
  verified: text('verified'),
  lastUpdated: text('last_updated'),
  createdAt: text('created_at'),
  updatedAt: text('updated_at'),
});
